services:
  robotmanagementsystem:
    image: robotmanagementsystem
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - robot_data:/app/data
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:8080
      - ASPNETCORE_ENVIRONMENT=Development
        
      # SQLite connection string
      - ConnectionStrings__Default=Data Source=data/robotmanagementsystem.db
  
volumes:
  robot_data: