<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="BlazorJWT.BlazoredLocalStorage" Version="1.0.1-tags-v1-0-0.1" />
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.3"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="10.0.3" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
        <PackageReference Include="MudBlazor" Version="9.1.0" />
        <PackageReference Include="MudBlazor.ThemeManager" Version="4.0.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RobotManagementSystem.Shared\RobotManagementSystem.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Modals\" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="Microsoft.Extensions.Http">
        <HintPath>..\..\..\..\..\.dotnet\packs\Microsoft.AspNetCore.App.Ref\10.0.5\ref\net10.0\Microsoft.Extensions.Http.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
