name: ASP.NET Core Continuous Integration (CI)

on: 
  push: 
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Display dotnet version
        run: dotnet --version

      - name: Restore dependencies 
        run: dotnet restore

      - name: Build SLN
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test --configuration Release --no-build

      - name: Build Docker compose services
        run: docker compose build
    
      - name: Run Docker Container
        run: docker compose up -d
        
      -name: Chekck backend health (try for 30 seconds three times)
               - run: |
               - for i in {1..30}; do
               - if curl --fail http://localhost:5085/health; then
               - echo "Backend is healthy"
               - exit 0
               - fi

               - echo "Backend is not ready yet..."
               - docker compose ps
               - sleep 3
               - done

               - echo "Backend did not become healthy"
               - docker compose logs robotmanagementsystem
               - exit 1
        
      - name: Stop Docker Container
        if: always()
        run: docker compose down